#             _ _                  _    _
#   ___ _   _| | |_ _   _ _ __ ___| | _(_)_ __   __ _ ___
#  / __| | | | | __| | | | '__/ _ \ |/ / | '_ \ / _` / __|
# | (__| |_| | | |_| |_| | | |  __/   <| | | | | (_| \__ \
#  \___|\__,_|_|\__|\__,_|_|  \___|_|\_\_|_| |_|\__, |___/
#                                               |___/

version: 2
executorType: docker
containerInfo:
  - image: culturekings/php-composer
    env:
      - APP_ENV=local
      - APP_DEBUG=true
stages:
  build:
    workDir: /var/www/html
    steps:
      - type: shell
        name: Install System Packages
        command: apt-get update && apt-get -y install git unzip zlib1g-dev
      - type: checkout
      - type: shell
        name: Install PHP Extensions
        command: |
          pecl install xdebug
          docker-php-ext-enable xdebug
      - type: shell
        name: Install Project Dependencies
        command: php composer.phar install -o --prefer-dist --no-interaction
      - type: shell
        name: Run Tests
        command: vendor/bin/phpspec run --format=pretty
      - type: shell
        name: Run Coding Standards
        command: |
          vendor/bin/phpcs --config-set installed_paths vendor/culturekings/symfony2-coding-standard
          vendor/bin/phpcs
      - type: shell
        name: Update Code Coverage
        command: |
          mkdir -p build/logs
          vendor/bin/coveralls -v -x coverage_clover.xml
