#             _ _                  _    _
#   ___ _   _| | |_ _   _ _ __ ___| | _(_)_ __   __ _ ___
#  / __| | | | | __| | | | '__/ _ \ |/ / | '_ \ / _` / __|
# | (__| |_| | | |_| |_| | | |  __/   <| | | | | (_| \__ \
#  \___|\__,_|_|\__|\__,_|_|  \___|_|\_\_|_| |_|\__, |___/
#                                               |___/

version: 2
executorType: docker
containerInfo:
  - image: php:7.0-fpm
    env:
      - APP_ENV=local
      - APP_DEBUG=true
stages:
  build:
    workDir: /code
    steps:
      - type: checkout
      - type: shell
        name: Install Composer
        command: |
          php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
          php -r "if (hash_file('SHA384', 'composer-setup.php') === '55d6ead61b29c7bdee5cccfb50076874187bd9f21f65d8991d46ec5cc90518f447387fb9f76ebae1fbbacf329e583e30') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
          php composer-setup.php
          php -r "unlink('composer-setup.php');"
          composer global config repositories.coding-standard vcs https://github.com/culturekings/Symfony2-coding-standard.git
      - type: shell
        name: Install Project Dependencies
        command: php composer.phar install -o --prefer-dist --no-interaction
      - type: shell
        name: Run Tests
        command: vendor/bin/phpspec run --format=pretty
      - type: shell
        name: Run Coding Standards
        command: |
          vendor/bin/phpcs --config-set installed_paths vendor/culturekings/symfony2-coding-standard
          vendor/bin/phpcs
      - type: shell
        name: Update Code Coverage
        command: vendor/bin/coveralls -v -x coverage_clover.xml
