CultureKings\Afterpay\Model\Merchant\Configuration:
  exclusion_policy: NONE
  properties:
    type:
      type: string
    description:
      type: string
    minimumAmount:
      type: CultureKings\Afterpay\Model\Money
      serialized_name: minimumAmount
    maximumAmount:
      type: CultureKings\Afterpay\Model\Money
      serialized_name: maximumAmount
